# Generated by Django 4.2.27 on 2026-02-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('is_safe', models.BooleanField(default=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('times_seen', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('reported_to_company', models.BooleanField(default=False)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
